const LEVEL_CONFIGS = Object.freeze({
  1: Object.freeze({
    number: 1,
    label: "Level 1",
    levelEndX: 2000,
    chickenCount: 7,
    littleChickenCount: 5,
    groundBottleCount: 9,
    startBottleCount: 6,
    coinCount: 16,
    chickenSpeedBase: 0.2,
    chickenSpeedRange: 0.2,
    littleChickenSpeedBase: 0.3,
    littleChickenSpeedRange: 0.2,
    coinMinY: 150,
    coinMaxY: 350,
    bossEnergy: 300,
    bossMoveSpeed: 5.0,
    bossChargeCooldown: 7000,
    bossHitCooldown: 400,
    bossMinX: 0,
    bossRightMargin: 200,
    bossAlertDistance: 350,
    score: Object.freeze({
      chickenStomp: 15,
      littleChickenStomp: 20,
      chickenBottleKill: 25,
      littleChickenBottleKill: 40,
      coinPickup: 5,
      bottlePickup: 2,
      bottleThrow: 3,
      bossStomp: 75,
      bossBottleHit: 40,
      bossChargeDodge: 150,
      bossKill: 300,
      remainingBottleMultiplier: 5,
      coinEndMultiplier: 15,
      remainingHealthMultiplier: 0.7,
    }),
  }),
  2: Object.freeze({
    number: 2,
    label: "Level 2",
    levelEndX: 2720,
    chickenCount: 10,
    littleChickenCount: 8,
    groundBottleCount: 11,
    startBottleCount: 5,
    coinCount: 22,
    chickenSpeedBase: 0.2,
    chickenSpeedRange: 0.3,
    littleChickenSpeedBase: 0.3,
    littleChickenSpeedRange: 0.35,
    coinMinY: 150,
    coinMaxY: 284,
    bossEnergy: 400,
    bossMoveSpeed: 5.5,
    bossChargeCooldown: 6000,
    bossHitCooldown: 350,
    bossMinX: 0,
    bossRightMargin: 200,
    bossAlertDistance: 350,
    score: Object.freeze({
      chickenStomp: 20,
      littleChickenStomp: 25,
      chickenBottleKill: 30,
      littleChickenBottleKill: 50,
      coinPickup: 8,
      bottlePickup: 5,
      bottleThrow: 5,
      bossStomp: 100,
      bossBottleHit: 50,
      bossChargeDodge: 220,
      bossKill: 500,
      remainingBottleMultiplier: 10,
      coinEndMultiplier: 20,
      remainingHealthMultiplier: 0.8,
    }),
  }),
  3: Object.freeze({
    number: 3,
    label: "Level 3",
    levelEndX: 3440,
    chickenCount: 13,
    littleChickenCount: 11,
    groundBottleCount: 13,
    startBottleCount: 4,
    coinCount: 28,
    chickenSpeedBase: 0.2,
    chickenSpeedRange: 0.4,
    littleChickenSpeedBase: 0.3,
    littleChickenSpeedRange: 0.5,
    coinMinY: 150,
    coinMaxY: 217,
    bossEnergy: 500,
    bossMoveSpeed: 6.0,
    bossChargeCooldown: 5000,
    bossHitCooldown: 300,
    bossMinX: 0,
    bossRightMargin: 200,
    bossAlertDistance: 350,
    score: Object.freeze({
      chickenStomp: 25,
      littleChickenStomp: 30,
      chickenBottleKill: 35,
      littleChickenBottleKill: 60,
      coinPickup: 12,
      bottlePickup: 8,
      bottleThrow: 8,
      bossStomp: 125,
      bossBottleHit: 60,
      bossChargeDodge: 300,
      bossKill: 1000,
      remainingBottleMultiplier: 25,
      coinEndMultiplier: 30,
      remainingHealthMultiplier: 1.2,
    }),
  }),
});

/**
 * Returns the configuration for one game level.
 *
 * @param {number} levelNumber - Requested level number.
 * @returns {Object} Level configuration.
 */
function getLevelConfig(levelNumber) {
  return LEVEL_CONFIGS[levelNumber] || LEVEL_CONFIGS[1];
}
